export const colors = {
    NAVY: 'navy',
    BLUE: 'blue',
    WHITE: 'white',
    TEAL: 'teal',
    OLIVE: 'olive',
    GREEN: 'green',
    LIME: 'lime',
    YELLOW: 'yellow',
    ORANGE: 'orange',
    RED: 'red',
    MAROON: 'maroon',
    FUCHSIA: 'fuchsia',
    PURPLE: 'purple',
    BLACK: 'black',
    GREY: 'grey',
    SILVER: 'silver',
}